# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:06
from __future__ import unicode_literals

import battle.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('task_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattleHashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typos', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=140, validators=[battle.models.hashtag_validator])),
            ],
        ),
        migrations.AddField(
            model_name='battlehashtags',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Hashtag'),
        ),
        migrations.AddField(
            model_name='battle',
            name='hashtags',
            field=models.ManyToManyField(through='battle.BattleHashtags', to='battle.Hashtag'),
        ),
    ]
