# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehashtags',
            name='words',
            field=models.IntegerField(default=0),
        ),
    ]
